localDataIndic = {
    1: {"type": "Primaire", "formule": "Dernier mois renseigné", "frequence": "mensuelle"},
    2: {"type": "Primaire", "formule": "Dernier mois renseigné", "frequence": "mensuelle"},
    3: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    4: {"type": "Primaire", "formule": "Dernier mois renseigné", "frequence": "mensuelle"},
    5: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    6: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    7: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    8: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    9: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    10: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    11: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    12: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    13: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    14: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    15: {"type": "Primaire", "formule": "Dernier mois renseigné", "frequence": "mensuelle"},
    16: {"type": "Primaire", "formule": "Dernier mois renseigné", "frequence": "mensuelle"},
    17: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    18: {"type": "Primaire", "formule": "Dernier mois renseigné", "frequence": "mensuelle"},
    19: {"type": "Primaire", "formule": "Dernier mois renseigné", "frequence": "mensuelle"},
    20: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    21: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    22: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    23: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    24: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    25: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    26: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    27: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    28: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    29: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    30: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    31: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    32: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    33: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    34: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    35: {"type": "Primaire", "formule": "Dernier mois renseigné", "frequence": "mensuelle"},
    36: {"type": "Primaire", "formule": "Dernier mois renseigné", "frequence": "mensuelle"},
    37: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    38: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    39: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    40: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    41: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    42: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    43: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    44: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    45: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    46: {"type": "Primaire", "formule": "Dernier mois renseigné", "frequence": "mensuelle"},
    47: {"type": "Primaire", "formule": "Dernier mois renseigné", "frequence": "mensuelle"},
    48: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    49: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    50: {"type": "Primaire", "formule": "Dernier mois renseigné", "frequence": "mensuelle"},
    51: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    52: {"type": "Primaire", "formule": "Dernier mois renseigné", "frequence": "mensuelle"},
    53: {"type": "Primaire", "formule": "Dernier mois renseigné", "frequence": "mensuelle"},
    54: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    55: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    56: {"type": "Primaire", "formule": "Dernier mois renseigné", "frequence": "mensuelle"},
    57: {"type": "Primaire", "formule": "Dernier mois renseigné", "frequence": "mensuelle"},
    58: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    59: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    60: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    61: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    62: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    63: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    64: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    65: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    66: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    67: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    68: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    69: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    70: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    71: {"type": "Primaire", "formule": "Dernier mois renseigné", "frequence": "mensuelle"},
    72: {"type": "Primaire", "formule": "Dernier mois renseigné", "frequence": "mensuelle"},
    73: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    74: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    75: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    76: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    77: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    78: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    79: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    80: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    81: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    82: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    83: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    84: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    85: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    86: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    87: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    88: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    89: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    90: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    91: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    92: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    93: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    94: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    95: {"type": "Primaire", "formule": "Dernier mois renseigné", "frequence": "mensuelle"},
    96: {"type": "Primaire", "formule": "Dernier mois renseigné", "frequence": "mensuelle"},
    97: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    98: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    99: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    100: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    101: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    102: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    103: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    104: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    105: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    106: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    107: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    108: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    109: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    110: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    111: {"type": "Test", "formule": "", "frequence": "mensuelle"},
    112: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    113: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    114: {"type": "Test", "formule": "", "frequence": "mensuelle"},
    115: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    116: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    117: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    118: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    119: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    120: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    121: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    122: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    123: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    124: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    125: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    126: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    127: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    128: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    129: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    130: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    131: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    132: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    133: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    134: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    135: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    136: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    137: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    138: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    139: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    140: {"type": "Primaire", "formule": "Dernier mois renseigné", "frequence": "mensuelle"},
    141: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    142: {"type": "Primaire", "formule": "Moyenne", "frequence": "mensuelle"},
    143: {"type": "Primaire", "formule": "Moyenne", "frequence": "mensuelle"},
    144: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    145: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    146: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    147: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    148: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    149: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    150: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    151: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    152: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    153: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    154: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    155: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    156: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    157: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    158: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    159: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    160: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    161: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    162: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    163: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    164: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    165: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    166: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    167: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    168: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    169: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    170: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    171: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    172: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    173: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    174: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    175: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    176: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    177: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    178: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    179: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    180: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    181: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    182: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    183: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    184: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    185: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    186: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    187: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    188: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    189: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    190: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    191: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    192: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    193: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    194: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    195: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    196: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    197: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    198: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    199: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    200: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    201: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    202: {"type": "Primaire", "formule": "Dernier mois renseigné", "frequence": "mensuelle"},
    203: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    204: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    205: {"type": "Primaire", "formule": "Dernier mois renseigné", "frequence": "mensuelle"},
    206: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    207: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    208: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    209: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    210: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    211: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    212: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    213: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    214: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    215: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    216: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    217: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    218: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    219: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    220: {"type": "Primaire", "formule": "Dernier mois renseigné", "frequence": "mensuelle"},
    221: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    222: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    223: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    224: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    225: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    226: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    227: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    228: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    229: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    230: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    231: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    232: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    233: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    234: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    235: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    236: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    237: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    238: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    239: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    240: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    241: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    242: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    243: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    244: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    245: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    246: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    247: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    248: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    249: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    250: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    251: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    252: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    253: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    254: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    255: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    256: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    257: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    258: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    259: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    260: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    261: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    262: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    263: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    264: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    265: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    266: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    267: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    268: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    269: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    270: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    271: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    272: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    273: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    274: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    275: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    276: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    277: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    278: {"type": "Calculé", "formule": "", "frequence": "mensuelle"},
    279: {"type": "Primaire", "formule": "Somme", "frequence": "mensuelle"},
    280: {"type": "Calculé", "formule": "", "frequence": "mensuelle"}
}

calculated_keys = [3, 5, 7, 10, 12, 19, 23, 24, 27, 30, 31, 33, 36, 38, 40, 42, 44, 49, 50, 52, 65, 66, 67, 68, 78, 79, 80, 90, 91, 92, 93, 94, 95, 96, 101, 108, 113, 115, 116, 121, 122, 124, 125, 126, 129, 132, 133, 135, 138, 139, 141, 144, 147, 148, 149, 150, 151, 152, 153, 156, 157, 158, 159, 160, 163, 164, 165, 166, 167, 170, 171, 172, 173, 174, 177, 178, 179, 180, 181, 184, 186, 188, 190, 192, 197, 198, 199, 208, 212, 215, 216, 227, 231, 234, 236, 239, 240, 241, 244, 249, 253, 258, 259, 260, 262, 264, 269, 271, 274, 277, 280, 283, 285, 287]
#ajout : 23, 283, 285, 287, 216